vehicles:
  - namespace: "px4_1"
    target_system: 2
    position:
      x: 0.0
      y: 0.0
      z: 10.0
  - namespace: "px4_2"
    target_system: 3
    position:
      x: 32.0
      y: -15.0
      z: 10.0
  - namespace: "px4_3"
    target_system: 4
    position:
      x: 3.0
      y: 49.0
      z: 10.0

